# rat.py

RAT_PROJECTS = {
    "bosentan_highdose": [
        "bosentan_highdose_Day_1_Rat_1.zip",
        "bosentan_highdose_Day_1_Rat_2.zip",
        "bosentan_highdose_Day_1_Rat_3.zip",
        "bosentan_highdose_Day_1_Rat_4.zip",
        "bosentan_highdose_Day_2_Rat_1.zip",
        "bosentan_highdose_Day_2_Rat_2.zip",
        "bosentan_highdose_Day_2_Rat_3.zip",
        "bosentan_highdose_Day_2_Rat_4.zip"
    ],
    "drug_effects": [
        "drug_effects_Asunaprevir_Day 1_Rat 1.zip",
        "drug_effects_Asunaprevir_Day 1_Rat 2.zip",
        "drug_effects_Asunaprevir_Day 1_Rat 3.zip",
        "drug_effects_Asunaprevir_Day 1_Rat 4.zip",
        "drug_effects_Asunaprevir_Day 1_Rat 5.zip",
        "drug_effects_Asunaprevir_Day 1_Rat 6.zip",
        "drug_effects_Asunaprevir_Day 2_Rat 1.zip",
        "drug_effects_Asunaprevir_Day 2_Rat 2.zip",
        "drug_effects_Asunaprevir_Day 2_Rat 3.zip",
        "drug_effects_Asunaprevir_Day 2_Rat 4.zip",
        "drug_effects_Asunaprevir_Day 2_Rat 5.zip",
        "drug_effects_Asunaprevir_Day 2_Rat 6.zip",
        "drug_effects_Bosentan_Day_1_Rat_1.zip",
        "drug_effects_Bosentan_Day_1_Rat_2.zip",
        "drug_effects_Bosentan_Day_1_Rat_3.zip",
        "drug_effects_Bosentan_Day_1_Rat_4.zip",
        "drug_effects_Bosentan_Day_1_Rat_5.zip",
        "drug_effects_Bosentan_Day_1_Rat_6.zip",
        "drug_effects_Bosentan_Day_2_Rat_1.zip",
        "drug_effects_Bosentan_Day_2_Rat_2.zip",
        "drug_effects_Bosentan_Day_2_Rat_3.zip",
        "drug_effects_Bosentan_Day_2_Rat_4.zip",
        "drug_effects_Bosentan_Day_2_Rat_5.zip",
        "drug_effects_Bosentan_Day_2_Rat_6.zip",
        "drug_effects_Cyclosporin_A_Day_1_Rat_1.zip",
        "drug_effects_Cyclosporin_A_Day_1_Rat_2.zip",
        "drug_effects_Cyclosporin_A_Day_1_Rat_3.zip",
        "drug_effects_Cyclosporin_A_Day_1_Rat_4.zip",
        "drug_effects_Cyclosporin_A_Day_1_Rat_5.zip",
        "drug_effects_Cyclosporin_A_Day_1_Rat_6.zip",
        "drug_effects_Cyclosporin_A_Day_2_Rat_1.zip",
        "drug_effects_Cyclosporin_A_Day_2_Rat_2.zip",
        "drug_effects_Cyclosporin_A_Day_2_Rat_3.zip",
        "drug_effects_Cyclosporin_A_Day_2_Rat_4.zip",
        "drug_effects_Cyclosporin_A_Day_2_Rat_5.zip",
        "drug_effects_Cyclosporin_A_Day_2_Rat_6.zip",
        "drug_effects_Ketoconazole_Day_1_Rat_1.zip",
        "drug_effects_Ketoconazole_Day_1_Rat_2.zip",
        "drug_effects_Ketoconazole_Day_1_Rat_3.zip",
        "drug_effects_Ketoconazole_Day_1_Rat_4.zip",
        "drug_effects_Ketoconazole_Day_1_Rat_5.zip",
        "drug_effects_Ketoconazole_Day_1_Rat_6.zip",
        "drug_effects_Ketoconazole_Day_2_Rat_1.zip",
        "drug_effects_Ketoconazole_Day_2_Rat_2.zip",
        "drug_effects_Ketoconazole_Day_2_Rat_3.zip",
        "drug_effects_Ketoconazole_Day_2_Rat_4.zip",
        "drug_effects_Ketoconazole_Day_2_Rat_5.zip",
        "drug_effects_Ketoconazole_Day_2_Rat_6.zip",
        "drug_effects_Pioglitazone_Day 1_Rat 1.zip",
        "drug_effects_Pioglitazone_Day 1_Rat 2.zip",
        "drug_effects_Pioglitazone_Day 1_Rat 3.zip",
        "drug_effects_Pioglitazone_Day 1_Rat 4.zip",
        "drug_effects_Pioglitazone_Day 1_Rat 5.zip",
        "drug_effects_Pioglitazone_Day 1_Rat 6.zip",
        "drug_effects_Pioglitazone_Day 2_Rat 1.zip",
        "drug_effects_Pioglitazone_Day 2_Rat 2.zip",
        "drug_effects_Pioglitazone_Day 2_Rat 3.zip",
        "drug_effects_Pioglitazone_Day 2_Rat 4.zip",
        "drug_effects_Pioglitazone_Day 2_Rat 5.zip",
        "drug_effects_Pioglitazone_Day 2_Rat 6.zip",
        "drug_effects_Rifampicin_Day_1_Rat_1.zip",
        "drug_effects_Rifampicin_Day_1_Rat_2.zip",
        "drug_effects_Rifampicin_Day_1_Rat_3.zip",
        "drug_effects_Rifampicin_Day_1_Rat_4.zip",
        "drug_effects_Rifampicin_Day_2_Rat_1.zip",
        "drug_effects_Rifampicin_Day_2_Rat_2.zip",
        "drug_effects_Rifampicin_Day_2_Rat_3.zip",
        "drug_effects_Rifampicin_Day_2_Rat_4.zip"
    ],
    "field_strength": [
        "field_strength_Day_1_Rat_1.zip",
        "field_strength_Day_1_Rat_2.zip",
        "field_strength_Day_1_Rat_3.zip",
        "field_strength_Day_1_Rat_4.zip",
        "field_strength_Day_1_Rat_5.zip",
        "field_strength_Day_1_Rat_6.zip",
        "field_strength_Day_2_Rat_1.zip",
        "field_strength_Day_2_Rat_2.zip",
        "field_strength_Day_2_Rat_3.zip",
        "field_strength_Day_2_Rat_4.zip",
        "field_strength_Day_2_Rat_5.zip",
        "field_strength_Day_2_Rat_6.zip"
    ],
    "relaxivity": [
        "relaxivity_B_SD-abcc_rats_2019_Rat_1a.zip",
        "relaxivity_B_SD-abcc_rats_2019_Rat_2a.zip",
        "relaxivity_B_SD-abcc_rats_2019_Rat_3a.zip",
        "relaxivity_B_SD-abcc_rats_2019_Rat_4a.zip",
        "relaxivity_B_SD-abcc_rats_2019_Rat_5a.zip",
        "relaxivity_B_SD-abcc_rats_2019_Rat_6a.zip",
        "relaxivity_B_SD-abcc_rats_2019_Rat_7a.zip",
        "relaxivity_B_SD-abcc_rats_2019_Rat_8a.zip",
        "relaxivity_B_SD-abcc_rats_2019_Rat_9a.zip",
        "relaxivity_B_SD-abcc_rats_2019_Rat_10a.zip",
        "relaxivity_B_SD-abcc_rats_2019_Rat_11a.zip",
        "relaxivity_B_SD-abcc_rats_2019_Rat_12a.zip",
        "relaxivity_B_SD-abcc_rats_2019_Rat_13a.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_1.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_2.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_3.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_4.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_5.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_6.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_7.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_8.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_9.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_10.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_11.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_12.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_13.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_14.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_15.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_16.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_17.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_18.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_19.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_20.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_21.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_22.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_23.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_24.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_25.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_26.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_27.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_28.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_29.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_30.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_31.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_32.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_33.zip",
        "relaxivity_B_SDAbcc_HanWistar_2014_Rat_34.zip",
        "relaxivity_B_Wistar_Han_2018_Rat_1a.zip",
        "relaxivity_B_Wistar_Han_2018_Rat_2a.zip",
        "relaxivity_B_Wistar_Han_2018_Rat_3a.zip",
        "relaxivity_B_Wistar_Han_2018_Rat_4a.zip",
        "relaxivity_B_Wistar_Han_2018_Rat_5a.zip",
        "relaxivity_B_Wistar_Han_2018_Rat_6a.zip",
        "relaxivity_B_Wistar_Han_2018_Rat_7a.zip",
        "relaxivity_B_Wistar_Han_2018_Rat_8a.zip",
        "relaxivity_B_Wistar_Han_2018_Rat_9a.zip",
        "relaxivity_C_Rat_1.zip",
        "relaxivity_C_Rat_2.zip",
        "relaxivity_C_Rat_3.zip",
        "relaxivity_C_Rat_4.zip",
        "relaxivity_C_Rat_5.zip",
        "relaxivity_C_Rat_6.zip",
        "relaxivity_C_Rat_7.zip",
        "relaxivity_C_Rat_8.zip",
        "relaxivity_C_Rat_9.zip",
        "relaxivity_C_Rat_10.zip",
        "relaxivity_C_Rat_11.zip",
        "relaxivity_C_Rat_12.zip",
        "relaxivity_C_Rat_13.zip",
        "relaxivity_C_Rat_14.zip",
        "relaxivity_C_Rat_15.zip",
        "relaxivity_C_Rat_16.zip",
        "relaxivity_C_Rat_17.zip",
        "relaxivity_C_Rat_18.zip",
        "relaxivity_C_Rat_19.zip",
        "relaxivity_C_Rat_20.zip",
        "relaxivity_C_Rat_21.zip",
        "relaxivity_C_Rat_22.zip",
        "relaxivity_C_Rat_23.zip",
        "relaxivity_C_Rat_24.zip",
        "relaxivity_C_Rat_25.zip",
        "relaxivity_C_Rat_26.zip",
        "relaxivity_C_Rat_27.zip",
        "relaxivity_C_Rat_28.zip",
        "relaxivity_C_Rat_29.zip",
        "relaxivity_C_Rat_30.zip",
        "relaxivity_C_Rat_31.zip",
        "relaxivity_C_Rat_32.zip",
        "relaxivity_C_Rat_33.zip",
        "relaxivity_C_Rat_34.zip",
        "relaxivity_D_Han_Wistar2_Rat_1b.zip",
        "relaxivity_D_Han_Wistar2_Rat_2b.zip",
        "relaxivity_D_Han_Wistar2_Rat_3b.zip",
        "relaxivity_D_Han_Wistar2_Rat_4b.zip",
        "relaxivity_D_Han_Wistar2_Rat_5b.zip",
        "relaxivity_D_Han_Wistar2_Rat_6b.zip",
        "relaxivity_D_Han_Wistar2_Rat_7b.zip",
        "relaxivity_D_Han_Wistar2_Rat_8b.zip",
        "relaxivity_D_Han_Wistar2_Rat_9b.zip",
        "relaxivity_D_Han-Wistar1_Rat_1.zip",
        "relaxivity_D_Han-Wistar1_Rat_2.zip",
        "relaxivity_D_Han-Wistar1_Rat_3.zip",
        "relaxivity_D_Han-Wistar1_Rat_4.zip",
        "relaxivity_D_Han-Wistar1_Rat_5.zip",
        "relaxivity_D_Han-Wistar1_Rat_6.zip",
        "relaxivity_D_Han-Wistar1_Rat_7.zip",
        "relaxivity_D_Han-Wistar1_Rat_8.zip",
        "relaxivity_D_Han-Wistar1_Rat_9.zip",
        "relaxivity_D_Han-Wistar1_Rat_10.zip",
        "relaxivity_D_Han-Wistar1_Rat_11.zip",
        "relaxivity_D_Han-Wistar1_Rat_12.zip",
        "relaxivity_D_Han-Wistar1_Rat_13.zip",
        "relaxivity_D_Han-Wistar1_Rat_14.zip",
        "relaxivity_D_Han-Wistar1_Rat_15.zip",
        "relaxivity_E_Rat_1.zip",
        "relaxivity_E_Rat_2.zip",
        "relaxivity_E_Rat_3.zip",
        "relaxivity_E_Rat_4.zip",
        "relaxivity_E_Rat_5.zip",
        "relaxivity_E_Rat_6.zip",
        "relaxivity_E_Rat_7.zip",
        "relaxivity_E_Rat_8.zip",
        "relaxivity_E_Rat_9.zip",
        "relaxivity_E_Rat_10.zip",
        "relaxivity_E_Rat_11.zip",
        "relaxivity_E_Rat_12.zip",
        "relaxivity_E_Rat_12b.zip",
        "relaxivity_E_Rat_13.zip",
        "relaxivity_E_Rat_13b.zip",
        "relaxivity_E_Rat_14.zip",
        "relaxivity_E_Rat_15.zip"
    ],
    "repeat_dose": [
        "repeat_dose_A_Rifampicin_clinical dose_Day_1_Rat 1.zip",
        "repeat_dose_A_Rifampicin_clinical dose_Day_1_Rat 4.zip",
        "repeat_dose_A_Rifampicin_clinical dose_Day_1_Rat 7.zip",
        "repeat_dose_A_Rifampicin_clinical dose_Day_1_Rat 10.zip",
        "repeat_dose_A_Rifampicin_clinical dose_Day_2_Rat 1.zip",
        "repeat_dose_A_Rifampicin_clinical dose_Day_2_Rat 4.zip",
        "repeat_dose_A_Rifampicin_clinical dose_Day_2_Rat 7.zip",
        "repeat_dose_A_Rifampicin_clinical dose_Day_2_Rat 10.zip",
        "repeat_dose_A_Rifampicin_clinical dose_Day_3_Rat 1.zip",
        "repeat_dose_A_Rifampicin_clinical dose_Day_3_Rat 4.zip",
        "repeat_dose_A_Rifampicin_clinical dose_Day_3_Rat 7.zip",
        "repeat_dose_A_Rifampicin_clinical dose_Day_3_Rat 10.zip",
        "repeat_dose_A_Rifampicin_clinical dose_Day_4_Rat 1.zip",
        "repeat_dose_A_Rifampicin_clinical dose_Day_4_Rat 4.zip",
        "repeat_dose_A_Rifampicin_clinical dose_Day_4_Rat 7.zip",
        "repeat_dose_A_Rifampicin_clinical dose_Day_4_Rat 10.zip",
        "repeat_dose_A_Rifampicin_high dose_Day_1_Rat 2.zip",
        "repeat_dose_A_Rifampicin_high dose_Day_1_Rat 5.zip",
        "repeat_dose_A_Rifampicin_high dose_Day_1_Rat 8.zip",
        "repeat_dose_A_Rifampicin_high dose_Day_1_Rat 11.zip",
        "repeat_dose_A_Rifampicin_high dose_Day_2_Rat 2.zip",
        "repeat_dose_A_Rifampicin_high dose_Day_2_Rat 5.zip",
        "repeat_dose_A_Rifampicin_high dose_Day_2_Rat 8.zip",
        "repeat_dose_A_Rifampicin_high dose_Day_2_Rat 11.zip",
        "repeat_dose_A_Rifampicin_high dose_Day_3_Rat 2.zip",
        "repeat_dose_A_Rifampicin_high dose_Day_3_Rat 5.zip",
        "repeat_dose_A_Rifampicin_high dose_Day_3_Rat 8.zip",
        "repeat_dose_A_Rifampicin_high dose_Day_3_Rat 11.zip",
        "repeat_dose_A_Rifampicin_high dose_Day_4_Rat 2.zip",
        "repeat_dose_A_Rifampicin_high dose_Day_4_Rat 5.zip",
        "repeat_dose_A_Rifampicin_high dose_Day_4_Rat 8.zip",
        "repeat_dose_A_Rifampicin_high dose_Day_4_Rat 11.zip",
        "repeat_dose_A_Saline_Day_1_Rat 3.zip",
        "repeat_dose_A_Saline_Day_1_Rat 6.zip",
        "repeat_dose_A_Saline_Day_1_Rat 9.zip",
        "repeat_dose_A_Saline_Day_1_Rat 12.zip",
        "repeat_dose_A_Saline_Day_2_Rat 3.zip",
        "repeat_dose_A_Saline_Day_2_Rat 6.zip",
        "repeat_dose_A_Saline_Day_2_Rat 9.zip",
        "repeat_dose_A_Saline_Day_2_Rat 12.zip",
        "repeat_dose_A_Saline_Day_3_Rat 3.zip",
        "repeat_dose_A_Saline_Day_3_Rat 6.zip",
        "repeat_dose_A_Saline_Day_3_Rat 9.zip",
        "repeat_dose_A_Saline_Day_3_Rat 12.zip",
        "repeat_dose_A_Saline_Day_4_Rat 3.zip",
        "repeat_dose_A_Saline_Day_4_Rat 6.zip",
        "repeat_dose_A_Saline_Day_4_Rat 9.zip",
        "repeat_dose_A_Saline_Day_4_Rat 12.zip",
        "repeat_dose_D_Cyclosporine_A_Day_1_Rat 1.zip",
        "repeat_dose_D_Cyclosporine_A_Day_1_Rat 2.zip",
        "repeat_dose_D_Cyclosporine_A_Day_1_Rat 7.zip",
        "repeat_dose_D_Cyclosporine_A_Day_1_Rat 8.zip",
        "repeat_dose_D_Cyclosporine_A_Day_1_Rat 11.zip",
        "repeat_dose_D_Cyclosporine_A_Day_1_Rat 12.zip",
        "repeat_dose_D_Cyclosporine_A_Day_1_Rat 13.zip",
        "repeat_dose_D_Cyclosporine_A_Day_2_Rat 1.zip",
        "repeat_dose_D_Cyclosporine_A_Day_2_Rat 2.zip",
        "repeat_dose_D_Cyclosporine_A_Day_2_Rat 7.zip",
        "repeat_dose_D_Cyclosporine_A_Day_2_Rat 8.zip",
        "repeat_dose_D_Cyclosporine_A_Day_2_Rat 11.zip",
        "repeat_dose_D_Cyclosporine_A_Day_2_Rat 12.zip",
        "repeat_dose_D_Cyclosporine_A_Day_2_Rat 13.zip",
        "repeat_dose_D_Cyclosporine_A_Day_3_Rat 1.zip",
        "repeat_dose_D_Cyclosporine_A_Day_3_Rat 2.zip",
        "repeat_dose_D_Cyclosporine_A_Day_3_Rat 7.zip",
        "repeat_dose_D_Cyclosporine_A_Day_3_Rat 8.zip",
        "repeat_dose_D_Cyclosporine_A_Day_3_Rat 11.zip",
        "repeat_dose_D_Cyclosporine_A_Day_3_Rat 12.zip",
        "repeat_dose_D_Saline_Day_1_Rat 3.zip",
        "repeat_dose_D_Saline_Day_1_Rat 4.zip",
        "repeat_dose_D_Saline_Day_1_Rat 5.zip",
        "repeat_dose_D_Saline_Day_1_Rat 6.zip",
        "repeat_dose_D_Saline_Day_1_Rat 9.zip",
        "repeat_dose_D_Saline_Day_1_Rat 10.zip",
        "repeat_dose_D_Saline_Day_2_Rat 3.zip",
        "repeat_dose_D_Saline_Day_2_Rat 4.zip",
        "repeat_dose_D_Saline_Day_2_Rat 5.zip",
        "repeat_dose_D_Saline_Day_2_Rat 6.zip",
        "repeat_dose_D_Saline_Day_2_Rat 9.zip",
        "repeat_dose_D_Saline_Day_2_Rat 10.zip",
        "repeat_dose_D_Saline_Day_3_Rat 3.zip",
        "repeat_dose_D_Saline_Day_3_Rat 4.zip",
        "repeat_dose_D_Saline_Day_3_Rat 5.zip",
        "repeat_dose_D_Saline_Day_3_Rat 6.zip",
        "repeat_dose_D_Saline_Day_3_Rat 9.zip",
        "repeat_dose_D_Saline_Day_3_Rat 10.zip",
        "repeat_dose_G2_Bosentan_Day_1_Rat_1.zip",
        "repeat_dose_G2_Bosentan_Day_1_Rat_2.zip",
        "repeat_dose_G2_Bosentan_Day_1_Rat_3.zip",
        "repeat_dose_G2_Bosentan_Day_1_Rat_4.zip",
        "repeat_dose_G2_Bosentan_Day_1_Rat_5.zip",
        "repeat_dose_G2_Bosentan_Day_1_Rat_6.zip",
        "repeat_dose_G2_Bosentan_Day_2_Rat_1.zip",
        "repeat_dose_G2_Bosentan_Day_2_Rat_2.zip",
        "repeat_dose_G2_Bosentan_Day_2_Rat_3.zip",
        "repeat_dose_G2_Bosentan_Day_2_Rat_4.zip",
        "repeat_dose_G2_Bosentan_Day_2_Rat_5.zip",
        "repeat_dose_G2_Bosentan_Day_2_Rat_6.zip"
    ],
    "repeatability": [
        "repeatability_A_Rifampicin_Day_2_Rat_2.zip",
        "repeatability_A_Rifampicin_Day_2_Rat_4.zip",
        "repeatability_A_Saline_Day_1_Rat_1.zip",
        "repeatability_A_Saline_Day_1_Rat_2.zip",
        "repeatability_A_Saline_Day_1_Rat_3.zip",
        "repeatability_A_Saline_Day_1_Rat_4.zip",
        "repeatability_A_Saline_Day_2_Rat_1.zip",
        "repeatability_A_Saline_Day_2_Rat_3.zip",
        "repeatability_D_Rifampicin_Day_1_Rat_4.zip",
        "repeatability_D_Rifampicin_Day_1_Rat_5.zip",
        "repeatability_D_Rifampicin_Day_1_Rat_6.zip",
        "repeatability_D_Rifampicin_Day_2_Rat_4.zip",
        "repeatability_D_Rifampicin_Day_2_Rat_5.zip",
        "repeatability_D_Rifampicin_Day_2_Rat_6.zip",
        "repeatability_D_Saline_Day_1_Rat_1.zip",
        "repeatability_D_Saline_Day_1_Rat_2.zip",
        "repeatability_D_Saline_Day_1_Rat_3.zip",
        "repeatability_D_Saline_Day_2_Rat_1.zip",
        "repeatability_D_Saline_Day_2_Rat_2.zip",
        "repeatability_D_Saline_Day_2_Rat_3.zip",
        "repeatability_E_Rifampicin_Day_2_Rat_4.zip",
        "repeatability_E_Rifampicin_Day_2_Rat_5.zip",
        "repeatability_E_Rifampicin_Day_2_Rat_6.zip",
        "repeatability_E_Saline_Day_1_Rat_1.zip",
        "repeatability_E_Saline_Day_1_Rat_2.zip",
        "repeatability_E_Saline_Day_1_Rat_3.zip",
        "repeatability_E_Saline_Day_1_Rat_4.zip",
        "repeatability_E_Saline_Day_1_Rat_5.zip",
        "repeatability_E_Saline_Day_1_Rat_6.zip",
        "repeatability_E_Saline_Day_2_Rat_1.zip",
        "repeatability_E_Saline_Day_2_Rat_2.zip",
        "repeatability_E_Saline_Day_2_Rat_3.zip",
        "repeatability_G1_Rifampicin_Day_2_Rat_5.zip",
        "repeatability_G1_Rifampicin_Day_2_Rat_6.zip",
        "repeatability_G1_Rifampicin_Day_2_Rat_7.zip",
        "repeatability_G1_Rifampicin_Day_2_Rat_8.zip",
        "repeatability_G1_Rifampicin_Day_2_Rat_9.zip",
        "repeatability_G1_Saline_Day_1_Rat_1.zip",
        "repeatability_G1_Saline_Day_1_Rat_2.zip",
        "repeatability_G1_Saline_Day_1_Rat_3.zip",
        "repeatability_G1_Saline_Day_1_Rat_4.zip",
        "repeatability_G1_Saline_Day_1_Rat_5.zip",
        "repeatability_G1_Saline_Day_1_Rat_6.zip",
        "repeatability_G1_Saline_Day_1_Rat_7.zip",
        "repeatability_G1_Saline_Day_1_Rat_8.zip",
        "repeatability_G1_Saline_Day_1_Rat_9.zip",
        "repeatability_G1_Saline_Day_1_Rat_10.zip",
        "repeatability_G1_Saline_Day_1_Rat_12.zip",
        "repeatability_G1_Saline_Day_2_Rat_1.zip",
        "repeatability_G1_Saline_Day_2_Rat_2.zip",
        "repeatability_G1_Saline_Day_2_Rat_3.zip",
        "repeatability_G1_Saline_Day_2_Rat_4.zip",
        "repeatability_G1_Saline_Day_2_Rat_5.zip",
        "repeatability_G1_Saline_Day_2_Rat_10.zip",
        "repeatability_G1_Saline_Day_2_Rat_11.zip",
        "repeatability_G1_Saline_Day_2_Rat_12.zip"
    ],
    "saline_only": [
        "saline_only_Female_low_weight_Day_1_Rat_1.zip",
        "saline_only_Female_low_weight_Day_1_Rat_2.zip",
        "saline_only_Female_low_weight_Day_1_Rat_3.zip",
        "saline_only_Female_low_weight_Day_1_Rat_4.zip",
        "saline_only_Female_low_weight_Day_2_Rat_1.zip",
        "saline_only_Female_low_weight_Day_2_Rat_2.zip",
        "saline_only_Female_low_weight_Day_2_Rat_3.zip",
        "saline_only_Female_low_weight_Day_2_Rat_4.zip",
        "saline_only_Female_right_weight_Day_1_Rat_1.zip",
        "saline_only_Female_right_weight_Day_1_Rat_2.zip",
        "saline_only_Female_right_weight_Day_1_Rat_3.zip",
        "saline_only_Female_right_weight_Day_1_Rat_4.zip",
        "saline_only_Female_right_weight_Day_2_Rat_1.zip",
        "saline_only_Female_right_weight_Day_2_Rat_2.zip",
        "saline_only_Female_right_weight_Day_2_Rat_3.zip",
        "saline_only_Female_right_weight_Day_2_Rat_4.zip",
        "saline_only_Male_Day_1_Rat_1.zip",
        "saline_only_Male_Day_1_Rat_2.zip",
        "saline_only_Male_Day_1_Rat_3.zip",
        "saline_only_Male_Day_1_Rat_4.zip",
        "saline_only_Male_Day_2_Rat_1.zip",
        "saline_only_Male_Day_2_Rat_2.zip",
        "saline_only_Male_Day_2_Rat_3.zip",
        "saline_only_Male_Day_2_Rat_4.zip"
    ],
    "sex_rifampicin": [
        "sex_rifampicin_Female_Day_1_Rat_1.zip",
        "sex_rifampicin_Female_Day_1_Rat_2.zip",
        "sex_rifampicin_Female_Day_1_Rat_3.zip",
        "sex_rifampicin_Female_Day_1_Rat_4.zip",
        "sex_rifampicin_Female_Day_2_Rat_1.zip",
        "sex_rifampicin_Female_Day_2_Rat_2.zip",
        "sex_rifampicin_Female_Day_2_Rat_3.zip",
        "sex_rifampicin_Female_Day_2_Rat_4.zip",
        "sex_rifampicin_Male_Day_1_Rat_1.zip",
        "sex_rifampicin_Male_Day_1_Rat_2.zip",
        "sex_rifampicin_Male_Day_1_Rat_3.zip",
        "sex_rifampicin_Male_Day_1_Rat_4.zip",
        "sex_rifampicin_Male_Day_2_Rat_1.zip",
        "sex_rifampicin_Male_Day_2_Rat_2.zip",
        "sex_rifampicin_Male_Day_2_Rat_3.zip",
        "sex_rifampicin_Male_Day_2_Rat_4.zip"
    ],
    "zsf_rifampicin": [
        "zsf_rifampicin_Lean_Rifampicin_Day_1_Rat_5.zip",
        "zsf_rifampicin_Lean_Rifampicin_Day_1_Rat_6.zip",
        "zsf_rifampicin_Lean_Rifampicin_Day_1_Rat_7.zip",
        "zsf_rifampicin_Lean_Rifampicin_Day_1_Rat_8.zip",
        "zsf_rifampicin_Lean_Rifampicin_Day_2_Rat_5.zip",
        "zsf_rifampicin_Lean_Rifampicin_Day_2_Rat_6.zip",
        "zsf_rifampicin_Lean_Rifampicin_Day_2_Rat_7.zip",
        "zsf_rifampicin_Lean_Rifampicin_Day_2_Rat_8.zip",
        "zsf_rifampicin_Lean_Saline_Day_1_Rat_1.zip",
        "zsf_rifampicin_Lean_Saline_Day_1_Rat_3.zip",
        "zsf_rifampicin_Lean_Saline_Day_1_Rat_4.zip",
        "zsf_rifampicin_Lean_Saline_Day_2_Rat_1.zip",
        "zsf_rifampicin_Lean_Saline_Day_2_Rat_2.zip",
        "zsf_rifampicin_Lean_Saline_Day_2_Rat_3.zip",
        "zsf_rifampicin_Lean_Saline_Day_2_Rat_4.zip",
        "zsf_rifampicin_Obese_Rifampicin_Day_1_Rat_5.zip",
        "zsf_rifampicin_Obese_Rifampicin_Day_1_Rat_6.zip",
        "zsf_rifampicin_Obese_Rifampicin_Day_1_Rat_8.zip",
        "zsf_rifampicin_Obese_Rifampicin_Day_2_Rat_5.zip",
        "zsf_rifampicin_Obese_Rifampicin_Day_2_Rat_6.zip",
        "zsf_rifampicin_Obese_Rifampicin_Day_2_Rat_7.zip",
        "zsf_rifampicin_Obese_Rifampicin_Day_2_Rat_8.zip",
        "zsf_rifampicin_Obese_Saline_Day_1_Rat_1.zip",
        "zsf_rifampicin_Obese_Saline_Day_1_Rat_2.zip",
        "zsf_rifampicin_Obese_Saline_Day_1_Rat_3.zip",
        "zsf_rifampicin_Obese_Saline_Day_1_Rat_4.zip",
        "zsf_rifampicin_Obese_Saline_Day_2_Rat_1.zip",
        "zsf_rifampicin_Obese_Saline_Day_2_Rat_2.zip",
        "zsf_rifampicin_Obese_Saline_Day_2_Rat_3.zip",
        "zsf_rifampicin_Obese_Saline_Day_2_Rat_4.zip"
    ],
    "zsf_saline": [
        "zsf_saline_Lean_Rat_9.zip",
        "zsf_saline_Lean_Rat_10.zip",
        "zsf_saline_Lean_Rat_11.zip",
        "zsf_saline_Lean_Rat_12.zip",
        "zsf_saline_Lean_Rat_13.zip",
        "zsf_saline_Lean_Rat_14.zip",
        "zsf_saline_Lean_Rat_15.zip",
        "zsf_saline_Obese_Rat_25.zip",
        "zsf_saline_Obese_Rat_26.zip",
        "zsf_saline_Obese_Rat_27.zip",
        "zsf_saline_Obese_Rat_28.zip",
        "zsf_saline_Obese_Rat_29.zip",
        "zsf_saline_Obese_Rat_30.zip",
        "zsf_saline_Obese_Rat_31.zip",
        "zsf_saline_Obese_Rat_32.zip"
    ],
}
